### ISSUE TITLE
.

### ISSUE THREAD

**Issue by rogeriocamorim** [Merlin-dev/Merlin_v1#48]
.

**Comment by rogeriocamorim** [comment]
![image](https://user-images.githubusercontent.com/1370987/40581891-a335c3b0-613a-11e8-8ca6-0fe5f6df6594.png)

**Comment by ir0kez** [comment]
Don't worry. We will ban you soon as well.

Albion-Online Team.

**Comment by rogeriocamorim** [comment]
@ir0kez I will give you a hit my in game name is Mojar
